### ISSUE TITLE
Get warnings when exiting program

### ISSUE THREAD

**Issue by PythonCoderAS** [praw-dev/asyncpraw#10]
**Describe the bug**

When I exit my Discord bot, I get a lot of ResourceWarnings from unclosed sessions.

**To Reproduce**
1. Make reddit instance
2. Await a sleep.
3. Handle KeyboardInterrupt and instantiate new instance
4. Hit Ctrl + C
5. Wait 5 seconds
6. Hit Ctrl + C again

**Expected behavior**

Program exits without any warnings.

**Code/Logs**

Code: 
```python
import asyncpraw
import asyncio

reddit = asyncpraw.Reddit(<login info>)

async def main():
    await reddit.submission("asdfgh")
    await asyncio.sleep(1000)

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    try:
        loop.run_until_complete(main())
    except:
        reddit = asyncpraw.Reddit(<login info>)
        try:
            loop.run_until_complete(main())
        except:
            pass
```

Output: 
```
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x10c4f0c10>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x10c5346a0>, 0.68580921)]']
connector: <aiohttp.connector.TCPConnector object at 0x10c4f0c40>
```

**System Info**
 - OS: Mac OS 10.15.6
 - Python: 3.8.5
 - Async PRAW Version: 7.1.0

**Comment by PythonCoderAS** [comment]
I think the solution would be to implement `atexit` functions or use `__del__` to close the connections.

**Comment by LilSpazJoekp** [comment]
It needs `await session.close()` somewhere or switch to using using a context manager for the `ClientSession`.

**Comment by PythonCoderAS** [comment]
> It needs `await session.close()` somewhere or switch to using using a context manager for the `ClientSession`.

How about `Reddit.close()` to close the Session?

**Comment by LilSpazJoekp** [comment]
I feel like this is a issue for asyncprawcore

**Comment by PythonCoderAS** [comment]
I do not understand how asyncprawcore works, but I remember there being a `Session` class. I assume this Session class gets closed. On deletion, we can have it run its close method. We can then add another method onto the `Reddit` class to do the same thing.
