### ISSUE TITLE
asyncpraw uses update_checker which isn't async

### ISSUE THREAD

**Issue by DevilXD** [praw-dev/asyncpraw#167]
### Describe the solution you'd like

`update_checker` is a PyPi package that appears to be used by this library, and is imported here: https://github.com/praw-dev/asyncpraw/blob/207dae9a8952d86b5083754a747ac0a055f255a2/asyncpraw/reddit.py#L48

The package itself appears to be using `requests` to do the actual checking when the `Reddit` class is instanced, and this isn't async. This goes against the whole purpose of this library, in that all web requests are to be done in an asynchronous way. Please consider either [dropping it as a requirement,](https://github.com/praw-dev/asyncpraw/blob/master/setup.py#L69) or using some other library for this purpose. Alternatively, version check could be done "manually" from asyncpraw itself.

### Describe alternatives you've considered

Since there's a check for that package being installed, one can just uninstall the package. Having to uninstall it after every update is quite terrible from the design perspective though, I'd like not to be forced to use a library that handles requests in a non-async way.

**Comment by LilSpazJoekp** [comment]
Is it actually causing issues with it blocking a very tiny bit when the Reddit class is first initialized? In my testing it does not. 

The issue with rewriting the update checker to async is that currently it checks for updates in a part of code where awaiting an asynchronous call is not feasible.

**Comment by DevilXD** [comment]
Since all this does (presumably from my side) is display a helpful information for the developer, one can implement the version check in an asynchronous way, and then just launch a task that completes it inside the `__init__`. This works, isn't blocking, and isn't going to crash the entire application if it doesn't work:

```py
import asyncio

class Reddit:
    def __init__(self):
        asyncio.create_task(self.version_check())

    async def version_check(self):
        ...
```

The reason I've discovered it is because my application crashed on restart, due to some weird SSL error:

```py
  File "/home/ubuntu/Redv3_cogs/hirez/reddit.py", line 183, in __init__
    self.reddit = asyncpraw.Reddit(
  File "/home/ubuntu/Redv3/lib/python3.8/site-packages/asyncpraw/reddit.py", line 311, in __init__
    self._check_for_update()
  File "/home/ubuntu/Redv3/lib/python3.8/site-packages/asyncpraw/reddit.py", line 456, in _check_for_update
    update_check(__package__, __version__)
  File "/home/ubuntu/Redv3/lib/python3.8/site-packages/update_checker.py", line 184, in update_check
    result = checker.check(package_name, package_version)
  File "/home/ubuntu/Redv3/lib/python3.8/site-packages/update_checker.py", line 62, in wrapped
    retval = function(obj, package_name, package_version, **extra_data)
  File "/home/ubuntu/Redv3/lib/python3.8/site-packages/update_checker.py", line 139, in check
    data = query_pypi(
  File "/home/ubuntu/Redv3/lib/python3.8/site-packages/update_checker.py", line 74, in query_pypi
    response = requests.get(f"https://pypi.org/pypi/{package}/json", timeout=1)
  File "/home/ubuntu/Redv3/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/ubuntu/Redv3/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ubuntu/Redv3/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ubuntu/Redv3/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/ubuntu/Redv3/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/ubuntu/Redv3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/ubuntu/Redv3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/ubuntu/Redv3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/ubuntu/Redv3/lib/python3.8/site-packages/urllib3/connection.py", line 392, in connect
    self.ssl_context = create_urllib3_context(
  File "/home/ubuntu/Redv3/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 312, in create_urllib3_context
    context.options |= options
  File "/usr/lib/python3.8/ssl.py", line 602, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "/usr/lib/python3.8/ssl.py", line 602, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "/usr/lib/python3.8/ssl.py", line 602, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  [Previous line repeated 483 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
```

While this should probably also go up as the `requests` lib issue, as I said, I'd like to avoid using `requests` entirely in my project at all costs, no matter how much it's blocking or not.

**Comment by LilSpazJoekp** [comment]
Ah, it appears it isn't an issue with `requests` blocking since your Reddit initialization is done synchronously. 

That said, this appears to be an issue with either your environment or like you said with an upstream package.

The simplest fix for this, for now, is to set `check_for_updates` to `False` via any of the available configuration options.

**Comment by DevilXD** [comment]
Thank you, I'll go with it for now. Still though, please consider doing something about it. I expected an async package not to do any requests in a blocking manner, even if it's something as simple as checking for new version during initialization and "doesn't" block. The default timeout for the `requests` package is 10 seconds, which is the maximum time the creation of the `Reddit` object (and the entire application) can be blocked for, and may result in a `TimeoutError` (unless that's somehow handled by the `update_checker` package). I don't think that something this simple should cause crashes when it misfires. Personally, I'd just implement it on my own in an async way and run it in a task, so that even if it errors out, the task will contain any possible exceptions and won't cause the entire application to crash, or delay creating objects and their usage either. The worst that can happen is the developer getting the message slightly later.

**Comment by LilSpazJoekp** [comment]
> Still though, please consider doing something about it.

I have tried to find a workaround but none of them are acceptable to me.

There are multiple ways of initializing and the using the `asyncpraw.Reddit` class:

1. By calling it directly and setting it as a global variable (the most common way):
    ```py
    reddit = asyncpraw.Reddit(**settings)

    async def main():
        me = await reddit.user.me()
        print(me.name)

    if __name__ == '__main__':
        asyncio.run(main())
    ```
2. By calling it directly and setting it as a variable in an asynchronous function:
    ```py
    async def main():
        reddit = asyncpraw.Reddit(**settings)
        me = await reddit.user.me()
        print(me.name)

    if __name__ == '__main__':
        asyncio.run(main())
    ```
3. As an asynchronous context manager:
    ```py
    async def main():
        async with asyncpraw.Reddit(**settings) as reddit:
            me = await reddit.user.me()
            print(me.name)

    if __name__ == '__main__':
        asyncio.run(main())
    ```

Note: I'm skipping setting it as a variable in a regular synchronous function as it's functionally the same as #<span></span>1.

For each of the following I document my findings for the three common ways `asyncpraw.Reddit` is used.

1. Your suggestion [here](https://github.com/praw-dev/asyncpraw/issues/167#issuecomment-1046014158) is what I tried initially. While it does work in some cases, there are some instances where it does not work correctly:

    - For #<span></span>1 above the following occurs and the check is not ran:
        ```py
        Traceback (most recent call last):
          File "/Users/jkpayne/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-1/221.4165.171/PyCharm 2022.1 EAP.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1483, in _exec
              pydev_imports.execfile(file, globals, locals)  # execute the script
          File "/Users/jkpayne/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-1/221.4165.171/PyCharm 2022.1 EAP.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
              exec(compile(contents+"\n", file, 'exec'), glob, loc)
          File "/Users/jkpayne/Desktop/PythonProjects/asyncpraw/test.py", line 50, in <module>
              reddit = asyncpraw.Reddit(**settings)
          File "/Users/jkpayne/Desktop/PythonProjects/asyncpraw/asyncpraw/reddit.py", line 313, in __init__
              asyncio.create_task(self._check_for_update())
          File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/tasks.py", line 336, in create_task
              loop = events.get_running_loop()
        RuntimeError: no running event loop
        sys:1: RuntimeWarning: coroutine 'Reddit._check_for_update' was never awaited
        ```
    - #<span></span>2 worked correctly.
    - #<span></span>3 worked correctly.

2. The next thing I tried was this:
    ```py
    asyncio.run_coroutine_threadsafe(self._check_for_update(), asyncio.new_event_loop()) # _check_for_update is asynchronous
    ```

    - #<span></span>1 failed:
        ```py
        /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/dis.py:458: RuntimeWarning: coroutine 'Reddit._check_for_update' was never awaited
        for start, end, line in code.co_lines():
        RuntimeWarning: Enable tracemalloc to get the object allocation traceback
        Traceback (most recent call last):
          File "/Users/jkpayne/Desktop/PythonProjects/asyncprawcore/asyncprawcore/requestor.py", line 64, in request
              return await self._http.request(
          File "/Users/jkpayne/Desktop/PythonProjects/asyncpraw/.venv3.10/lib/python3.10/site-packages/aiohttp/client.py", line 448, in _request
              with timer:
          File "/Users/jkpayne/Desktop/PythonProjects/asyncpraw/.venv3.10/lib/python3.10/site-packages/aiohttp/helpers.py", line 635, in __enter__
              raise RuntimeError(
        RuntimeError: Timeout context manager should be used inside a task
        ```
    - #<span></span>2 failed:
        ```py
        /Users/jkpayne/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-1/221.4165.171/PyCharm 2022.1 EAP.app/Contents/plugins/python/helpers/pydev/_pydevd_frame_eval/pydevd_modify_bytecode.py:202: RuntimeWarning: coroutine 'Reddit._check_for_update' was never awaited
        InsertedCode = namedtuple('InsertedCode', ['offset', 'code_list'])
        RuntimeWarning: Enable tracemalloc to get the object allocation traceback
        ```
    - #<span></span>3 failed with the same error:
        ```py
        /Users/jkpayne/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-1/221.4165.171/PyCharm 2022.1 EAP.app/Contents/plugins/python/helpers/pydev/_pydevd_frame_eval/pydevd_modify_bytecode.py:202: RuntimeWarning: coroutine 'Reddit._check_for_update' was never awaited
        InsertedCode = namedtuple('InsertedCode', ['offset', 'code_list'])
        RuntimeWarning: Enable tracemalloc to get the object allocation traceback
        ```
There are other ways I've tried but none were consistent in calling an async function from sync code.

The only solution I will accept must work in all three different ways of initializing `asyncpraw.Reddit` that I listed above. A possible alternative is to move the check to an asynchronous function and convert `update_checker` to async. That would have placed either [here](https://github.com/praw-dev/asyncpraw/blob/207dae9a8952d86b5083754a747ac0a055f255a2/asyncpraw/reddit.py#L143) or [here](https://github.com/praw-dev/asyncpraw/blob/207dae9a8952d86b5083754a747ac0a055f255a2/asyncpraw/reddit.py#L967).

> I expected an async package not to do any requests in a blocking manner, even if it's something as simple as checking for new version during initialization and "doesn't" block. The default timeout for the requests package is 10 seconds, which is the maximum time the creation of the Reddit object (and the entire application) can be blocked for, and may result in a TimeoutError (unless that's somehow handled by the update_checker package).

The longest `update_checker` will block is [1 second](https://github.com/bboe/update_checker/blob/main/update_checker.py#L74). This *shouldn't* cause an issue but you're correct in that it should not block at all.

With all this said, I've talked to @bboe, the author of the `update_checker` package, and he said he'll work on converting it to async. After that I will work on changing it to call the update checker correctly.

**Comment by DevilXD** [comment]
> For #1 above the following occurs and the check is not ran
> `RuntimeError: no running event loop`

Creating a task via `asyncio.create_task` requires a running event loop. This may not be widely known, but `asyncio` has already deprecated `asyncio.get_event_loop`, and is going to (or already did) replace all internal calls with an equivalent of `get_running_loop` in the future, that raises a `RuntimeError` if there's no running loop. Following this, `aiohttp>=4.0.0` will **require** a running loop in order to instance `aiohttp.ClientSession` from `asyncprawcore`'s `Requestor` class, making this #1 example (initialising the `Reddit` instance outside of a coroutine) eventually unsupported. I know this isn't a pressing problem right now, but generally this will start raising deprecation warnings and eventually stop working altogether at some point. The documentation should be explicitly pushing people into instancing the class inside a coroutine to "future proof" their code because of this, but it's really up to maintainers to decide. I'm just pointing out that the main dependency used in this library (`aiohttp`) will eventually require you to not do it like this anyway.

If creating the `Reddit` object (and thus the `aiohttp.ClientSession`) really needs to be supported outside of a coroutine at the moment, a workaround is to do something like this:

```py
loop = asyncio.get_event_loop()
loop.create_task(self._check_for_update())
```

Note that `get_event_loop` is already deprecated as I mentioned, which is why it's less safe. Creating a task via `loop.create_task` instead of `asyncio.create_task` will always work, regardless if the loop is running or not. If the loop is not running at the time of task creation, the task will not run right away but still be scheduled, and will start execution once the loop starts running.

Regarding this:

```py
asyncio.run_coroutine_threadsafe(self._check_for_update(), asyncio.new_event_loop())
```

This creates a new, non-running event loop, and tries to run the coroutine in it. You end up with two separate event loops. It's not going to work.

..., or delay the creation of the session until the loop will be running, like this (more safe):

```py
class Reddit:
    # I know this is done from asyncprawcore and is more complicated than this, but it's just a demonstration
    def __init__(self):
        self._session = None  # session starts as None

    async def request(self, ...):
        # Note: this is a coro so the loop has to be running inside here
        # Session is created just before it's used to do a request
        if self._session is None:
            self._session = aiohttp.ClientSession(...)
        async with self._session.request(...) as response:
            return response
```

There's also another thing to point out here. As I've already mentioned above, creating a task requires a running event loop. Creating an `aiohttp.ClientSession` object also "requires" a running event loop, and doing so outside of a coroutine (which happens when one instances the `Reddit` class) currently raises a warning, unless a loop is explicitly passed in. It looks like `asyncprawcore` is doing exactly that:

https://github.com/praw-dev/asyncprawcore/blob/c08c5f0a3de4d1f760e298c4a4c0b390f1b4db72/asyncprawcore/requestor.py#L45-L48

This is a bandaid fix due to all of the above, and the error you've got is a byproduct of it. Both `asyncio` and `aiohttp` are moving towards `get_running_loop` and in general disallowing creation of async primitives outside of a running loop. For more information regarding this, please refer to:

https://github.com/aio-libs/aiohttp/issues/3072
https://docs.aiohttp.org/en/stable/faq.html#why-is-creating-a-clientsession-outside-of-an-event-loop-dangerous
https://github.com/aio-libs/aiohttp/blob/ca51ebd5ffb77f66218933e017a0c924f5810b4d/aiohttp/helpers.py#L290

With the creation of the `Reddit` instance inside a coroutine being properly enforced (and required in the future due to `aiohttp` imposing this restriction), my first solution of just `asyncio.create_task(self._check_for_update())` would work. Creation inside coroutines may as well start being at least suggested already, somewhere in the documentation. The best course of action would be to release a new breaking version of `asyncprawcore` and `asyncpraw` that enforces this in the nearest future, possibly with a couple of versions along the way that mention the deprecation. I think it's better to move on on this earlier than later.

**Comment by LilSpazJoekp** [comment]
Interesting. This isn't something I considered when creating the package. Would you be interested in creating a PR with the changes you suggest?

**Comment by DevilXD** [comment]
Sure, as much as my time will allow. Is it supposed to disallow session creation (and thus `Reddit` instance creation) outside coroutines right away, or merely serve a warning to the user first, where actual "disallowing" will be released later on? This 2nd approach would give library users some time to adjust their code, although in most cases it'd be as easy as copy-pasting the line that creates the `Reddit` instance from top-level code to inside a coroutine, like so:

```py
reddit = Reddit(...)

async def main():
    # use reddit

asyncio.run(main())
```
```py
async def main():
    reddit = Reddit(...)
    # use reddit

asyncio.run(main())
```

This change would have to touch on `asyncprawcore` instead of `asyncpraw` (here) since that's where session creation and management happens.

**Comment by LilSpazJoekp** [comment]
I would still like to allow the Reddit instance creation out side of coroutines and move the setup asyncprawcore execution to run on network first request. That way there shouldn't have to be a breaking change.

**Comment by DevilXD** [comment]
Sure, will do. Please note that this will still not let you setup an update check task without using `loop.create_task` and `asyncio.get_event_loop` which is deprecated though. This is why `asyncio` and `aiohttp` are pushing towards primitive creation inside coroutines, as I've pointed out. Doing it this way just moves the deprecated `asyncio.get_event_loop` call from `asyncprawcore` where the loop is passed to `aiohttp.ClientSession`, to this library where the loop is used to schedule a task on a non-running loop, and thus doesn't really get rid of the underlaying problem that's eventually going to require doing it "the proper way" anyway. Again, my suggestion here would be to at least mention this in the documentation, and start pushing towards disallowing `Reddit` instance creation outside of coroutines in the future.

**Comment by LilSpazJoekp** [comment]
Yes, my plan is to move the check for updates to first network request.
