### ISSUE TITLE
Bump aiofiles dependency

### ISSUE THREAD

**Issue by Luc1412** [praw-dev/asyncpraw#203]
### Describe the solution you'd like

Some months ago I PRed #181 to support newer version of aiofiles. Since then they switched from normal versioning to versioning which includes the year eg. `22.1.0 `.

I'm not fully sure how they handle breaking changes, but it would be nice to implement some solution which allows users to use newer aiofiles version.

**Comment by LilSpazJoekp** [comment]
Bumping the version isn't going to have any impact unless you're using the deprecated token manager utilities.

**Comment by Luc1412** [comment]
Bumping provides devs who use this wrapper + aiofiles the ability to use newer versions of aiofiles in their project as the version is  currently locked at `< 1`

**Comment by LilSpazJoekp** [comment]
Ah that's right. Feel free to open a PR to bump the version if you'd like.

**Comment by Luc1412** [comment]
Not entirely sure how to pin the version, as they didn't stated anything when they introduce breaking changes.

Any idea whether to just pin it to <= latest or something like < 23

**Comment by LilSpazJoekp** [comment]
Typically we pin to latest minor of the current version i.e., `aiofiles==23.*`. `aiofiles<23` will also work but the former will ensure the latest version instead of any version below 23.

**Comment by BjoernPetersen** [comment]
Could this be reopened?

**Comment by LilSpazJoekp** [comment]
Sure! Is there something that aiofiles added or uses that would make the newer version better?

**Comment by ShaneOss** [comment]
> Sure! Is there something that aiofiles added or uses that would make the newer version better?

Hi @LilSpazJoekp, I have another package with a dependency on a later version of aiofiles. Has this been fixed in the last release? I'm still seeing asyncpraw is locked <1.

**Comment by LilSpazJoekp** [comment]
The dev version is not pinned. We haven't pushed a new version yet however.

**Comment by ShaneOss** [comment]
> The dev version is not pinned. We haven't pushed a new version yet however.

Thanks @LilSpazJoekp! I couldn't find a dev branch. Any ETA for new version?

**Comment by LilSpazJoekp** [comment]
The master branch is the dev branch. You can install it with this command:

```shell
pip install --upgrade https://github.com/praw-dev/asyncpraw/archive/master.zip
```

> Any ETA for new version?

No ETA right now.
