### ISSUE TITLE
Use native contextlib.asynccontextmanager

### ISSUE THREAD

**Issue by qarkai** [praw-dev/asyncpraw#245]
### Describe the solution you'd like

Remove asyncio_extras dependency. It's used in `asyncpraw/util/token_manager.py` for `async_contextmanager` only.
`contextlib.asynccontextmanager` is available since Python 3.7.

### Additional context

https://docs.python.org/3/library/contextlib.html#contextlib.asynccontextmanager

**Comment by LilSpazJoekp** [comment]
This is a pretty simple change. Would you be interested in making it and opening a PR?

**Comment by qarkai** [comment]
I did. Not sure if pytest failures connected. Also don't know how to fix them.
