### ISSUE TITLE
Add support for inline media

### ISSUE THREAD

**Issue by SpyrosRoum** [praw-dev/asyncpraw#27]
With praw you can make a submission to a subreddit that also has inline media like images or gifs. I'd really like to be able to do the same with asyncpraw

[praw submit](https://praw.readthedocs.io/en/latest/code_overview/models/subreddit.html#praw.models.Subreddit.submit) vs [asyncpraw submit](https://asyncpraw.readthedocs.io/en/latest/code_overview/models/subreddit.html#asyncpraw.models.Subreddit.submit)

**Comment by LilSpazJoekp** [comment]
I am working on bringing this feature over. I should have it done soon.

**Comment by SpyrosRoum** [comment]
Thank you, I appreciate it!

**Comment by LilSpazJoekp** [comment]
No problem! I'll leave this issue open for the time being and close it when I get this done.
