### ISSUE TITLE
aiofiles version is locked to <1

### ISSUE THREAD

**Issue by sertraline** [praw-dev/asyncpraw#278]
### Describe the solution you'd like

I ran down into issues with poetry while trying to install this library. I use a library that depends on latest version of aiofiles (^23.*), but in setup.py asyncpraw is locked down to aiofiles <1:
```
   install_requires=[
        "aiofiles <1",
```
Which turns into dependency conflict. Then, the only available <1 version is 0.8.0, which was released in 2021. So I just wanted to ask if this is a typo or intended to be like that?

**Comment by LilSpazJoekp** [comment]
The aiofiles dependency can be updated. It has be unpinned in the master branch.

**Comment by sertraline** [comment]
thanks!
