### ISSUE TITLE
Published release with aiofiles<1 unpinned

### ISSUE THREAD

**Issue by NicolasNewman** [praw-dev/asyncpraw#284]
### Describe the solution you'd like

It seems that #278 resulted in the dependency `aiofiles` being unpinned in master. Unfortunately, there hasn't been a new release since Jul 2023. Is there a timeline on when there will be a published release containing that change? Unforuntately, I'm only able to install packages from PyPI for the codebase I'm working with so pulling the latest version from the master branch isn't an option for me.

**Comment by LilSpazJoekp** [comment]
Apologies, this slipped my mind. I'll get a release out soon.

**Comment by LilSpazJoekp** [comment]
Again, sorry for the long delay. This is now released.

**Comment by NicolasNewman** [comment]
Thank you for getting around to it!
