### ISSUE TITLE
New release for stream fix

### ISSUE THREAD

**Issue by rustom-ichhaporia** [praw-dev/asyncpraw#59]
It would be nice to have a new release for new people installing `asyncpraw` through pip that patched some of the recent changes. I'm thinking of [this issue](https://github.com/praw-dev/asyncpraw/issues/16) in particular, which patches the timeout of the `stream` function. The function is even highlighted through one of the only tutorials in the docs, which will actually experience a similar time out without the [patch](https://github.com/praw-dev/asyncpraw/pull/18) that was submitted by @cmays90. It has been almost a year since the last release, so many people aren't getting access to these patches, and pulling bleeding-edge versions of the code through a requirements.txt or `pip install` is inconvenient. I don't know what the current timeline is for the project, but a new release soon would be helpful.

**Comment by LilSpazJoekp** [comment]
I'll take care of that very shortly.

**Comment by LilSpazJoekp** [comment]
Got that released for ya!

**Comment by rustom-ichhaporia** [comment]
So quick -- thank you!
