### ISSUE TITLE
subreddit.flair() generator not working as intended

### ISSUE THREAD

**Issue by notaduck448** [praw-dev/asyncpraw#92]
**Describe the bug**
To get a list of users and flairs on a subreddit, you can use the `subreddit.flair()` generator. When looping through this generator without specifying the redditor argument, it should return the listings of ALL users and their flairs. Instead, it only returns the listing of the reddit user "None".

**To Reproduce**
On a subreddit in which you have the correct flair permissions, loop through the list of users and their flairs.

```py
reddit = Reddit(...)
sub = await reddit.subreddit("subreddit_goes_here")

async for flair in sub.flair():
  print(flair)
```

**Expected behavior**
A list of users and their flairs on the subreddit to be printed.

**Code/Logs**
Problem seems to be here [in this file](https://github.com/praw-dev/asyncpraw/blob/52b2ce04c77cb73b7c52a03fcde89bb82d00f69c/asyncpraw/models/reddit/subreddit.py#L1696) on line 1696.

```py
Subreddit._safely_add_arguments(generator_kwargs, "params", name=str(redditor))
generator_kwargs.setdefault("limit", None)
url = API_PATH["flairlist"].format(subreddit=self.subreddit)
return ListingGenerator(self.subreddit._reddit, url, **generator_kwargs)
```

If `redditor` is `None`, it will be converted to the string `'None'` and be treated as if you were literally searching for the flair of the user "None". This makes it impossible to call this generator without having the redditor argument added to `generator_kwargs`. It should just be:

```py
Subreddit._safely_add_arguments(generator_kwargs, "params", name=redditor)
generator_kwargs.setdefault("limit", None)
url = API_PATH["flairlist"].format(subreddit=self.subreddit)
return ListingGenerator(self.subreddit._reddit, url, **generator_kwargs)
```

without explicitly casting `redditor` to a string. This bug only affects the async version of the library and [behavior is working as intended in the main library](https://github.com/praw-dev/praw/blob/ca651d28ab18d5e59e126ad5011e1d40d2d877ac/praw/models/reddit/subreddit.py#L1611).

**Comment by LilSpazJoekp** [comment]
I'll get this fixed for ya
